### ISSUE TITLE
[ZM] Include HURUmap.Zambia here

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/HURUmap-apps#18]
We're consolidating these separate repos into one so lets' add the [HURUmap.Zambia](https://github.com/CodeForAfricaLabs/HURUmap.Zambia) files here following how it's been done for ke and tz.

**Comment by malgamves** [comment]
Where do I get the HURUmap.Zambia files from?

**Comment by malgamves** [comment]
Should I push to developer what I did before?
