### ISSUE TITLE
[IDEA] Add politician profiling

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/HURUmap-apps#25]
As a user, I'd also like to see who the politicians in my administrative area are while looking at the rest of the data.

**Comment by malgamves** [comment]
How would this be possible?

**Comment by DavidLemayian** [comment]
@malgamves Very early idea. I'm keeping this issue here to think through it and will improve the comment when I've had some more time to do so.

**Comment by DavidLemayian** [comment]
Closing to use #52 instead.
