### ISSUE TITLE
GitHub Link not working on webiste

### ISSUE THREAD

**Issue by malgamves** [CodeForAfrica/HURUmap-apps#35]
The to this GitHub repo on https://zambia.hurumap.org/topics returns an error.

Any idea why!? I could possibly fix it.

**Comment by phillipahereza** [comment]
@malgamves all the country instances were merged into one [repo](https://github.com/CodeForAfrica/HURUmap). And yes you can fix it, clone [this](https://github.com/CodeForAfrica/HURUmap) and make point the link to https://github.com/CodeForAfrica/HURUmap.  And make a PR. 
Thanks 👍

**Comment by malgamves** [comment]
Hey, I can't find the file for the Zambia page which is giving the error. Is it in the develop or master branch?? The master branch has the right Url.

The error is coming because ".Zambia" is being appended to the Url https://github.com/CodeForAfrica/HURUmap

Whats a fix??

**Comment by phillipahereza** [comment]
@malgamves this has been fixed
