### ISSUE TITLE
Update example images and all texts on Wazimap Kenya homepage

### ISSUE THREAD

**Issue by StephenAbbott** [CodeForAfrica/HURUmap-apps#4]
Text/images on http://kenya.wazimap.org are currently copied over from the South African Wazi website so we need to update text and images to use Kenya examples.

**Comment by longhotsummer** [comment]
We actually have those images in the old repo: https://github.com/CodeForAfrica/WAZImap.Kenya/tree/master/census/static/img/examples

**Comment by StephenAbbott** [comment]
Thanks @longhotsummer. Think @DavidLemayian has just moved the repo but good to know assets are there.
