### ISSUE TITLE
[FEATURE] Add chart image download in 'Chart Options' 

### ISSUE THREAD

**Issue by josephluvanda** [CodeForAfrica/HURUmap-apps#43]
## Description

As a user I would like to download the chart as an image to use elsewhere.

**Comment by tebajanga** [comment]
@DavidLemayian - Is there any update on this?

**Comment by DavidLemayian** [comment]
Good question @tebajanga. It looks like changes happened on CodeForAfricaLabs/wazimap instead of here. We should therefore move the changes.

Are you up to doing that?
