### ISSUE TITLE
Communication channel

### ISSUE THREAD

**Issue by malgamves** [CodeForAfrica/HURUmap-apps#65]
## Description
How do you guys communicate? Is there a channel we can discuss a few things besides Github? Would love to.

**Comment by DavidLemayian** [comment]
Thanks for getting in touch @malgamves. We're working on a [community forum right now on openAFRICA](https://github.com/CodeForAfricaLabs/openAFRICA/issues/21) to do this but more immediately, I'll add you to our Slack.

**Comment by malgamves** [comment]
Got the invitation. Thanks!
