### ISSUE TITLE
Hide Empty Sections

### ISSUE THREAD

**Issue by phillipahereza** [CodeForAfrica/HURUmap-apps#67]
## Description
Hide sections with missing data for regions 

## Screenshots
![screencapture-tanzania-hurumap-org-profiles-ward-779-iragua-2018-05-18-12_33_24](https://user-images.githubusercontent.com/13383422/40227649-c42cd904-5a97-11e8-9961-1db0840830f7.png)

**Comment by DavidLemayian** [comment]
Moved - https://github.com/CodeForAfricaLabs/HURUmap/issues/18
