### ISSUE TITLE
[WAJIBISHA] Sunset Wajibisha in HURUmap-apps

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/HURUmap-apps#78]
**Is your feature request related to a problem? Please describe.**
Wajibisha has stalled over a long time due to other pressing requirements and is not making enough movement quickly enough as part of the HURUmap ecosystem.

**Describe the solution you'd like**
Removen Wajibisha code + apps.

**Describe alternatives you've considered**
We're using simple Medium publication page and pointing people directly to a public Trello Team page.

**Additional context**
N/A

**Comment by kilemensi** [comment]
Migrated to PT.
