### ISSUE TITLE
Fix gender classification colours + arrangement

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/HURUmap-apps#8]
In the education section, the genders change colours and arrangement making it hard to quickly identify patterns.

Example visualisation [(link)](http://kenya.wazimap.org/embed/iframe.html?geoID=county-47&chartDataID=education-school_attendance_distribution&dataYear=2011&chartType=grouped_column&chartHeight=200&chartQualifier=Universe%3A+People+aged+3+years+and+older&chartTitle=School+attendance+by+sex&initialSort=&statType=scaled-percentage):

![screen shot 2016-05-06 at 11 17 01 am](https://cloud.githubusercontent.com/assets/877919/15069206/6585a4e4-137c-11e6-8bcb-7cea6c159e27.png)

**Comment by mevey** [comment]
This works  just as well.

Changing the conditions to order keys to the following. (Removing the 'whether data exists' check)
<img width="425" alt="screen shot 2016-05-17 at 1 09 05 pm" src="https://cloud.githubusercontent.com/assets/4598145/15318823/9bea53a6-1c30-11e6-8fce-e5ed9371adf8.png">
