### ISSUE TITLE
[OUR LAND] Define Datasets and Data Releases for set of data

### ISSUE THREAD

**Issue by KhadijaMahanga** [CodeForAfrica/HURUmap-apps#90]
Different data set on our_land such as agricultural sales statistic and DRDLR report to be defined to a  datasets and have release year.

**Comment by KhadijaMahanga** [comment]
This issue depends on an update of HURUmap-apps' `wazimap` package to include datasets releases. wazimap-za, a similar project, are using the 'git+https://github.com/OpenUpSA/wazimap.git@releases#egg=wazimap[gdal]' version of wazimap which include dataset and releases

**Comment by kilemensi** [comment]
Migrated to PT.
